- hosts: mycomputer
  tasks:
    - name: Get distro
      when: ansible_facts['os_family'] == "Debian"
      command:
        lsb_release -cs
      register: distro_name
    - name: Add Microsoft repository key
      when: ansible_facts['os_family'] == "Debian"
      apt_key:
        url: "https://packages.microsoft.com/keys/microsoft.asc"
        state: present
      become: yes
    - name: Add Azure CLI software repository
      when: ansible_facts['os_family'] == "Debian"
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ distro_name.stdout }} main"
        state: present
      become: true
    - name: Install the Azure CLI
      when: ansible_facts['os_family'] == "Debian"
      apt:
        name: azure-cli
        state: present
        force: true
      become: true
    - name: Install the Azure CLI
      when: ansible_facts['os_family'] == "Darwin"
      community.general.homebrew:
        name: azure-cli