- hosts: mycomputer
  vars:
    git_email: shilyndon@gmail.com
  tasks:
    # Git setup
    - name: Set Git name
      community.general.git_config:
        name: user.name
        scope: global
        value: "Lyndon Shi"
    - name: Set Git email
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ git_email }}"
    - name: Set Git editor
      community.general.git_config:
        name: core.editor
        scope: global
        value: vim

    # Set up vim.
    - name: Copying ~/.vimrc
      copy:
        src: "{{ playbook_dir }}/.vimrc"
        dest: "{{ ansible_env.HOME }}/.vimrc"

    # Set up .bashrc.
    - name: Updating ~/.bashrc to print timestamp
      blockinfile:
        dest: "{{ ansible_env.HOME }}/.bashrc"
        insertafter: EOF
        create: yes
        marker: "# <-- {mark} ANSIBLE MANAGED BLOCK FOR TIMESTAMP -->"
        marker_begin: "BEGIN"
        marker_end: "END"
        block: |
          PS1="\t $PS1" # Always show timestamp in case of WSL clock drift.