- hosts: mycomputer
  tasks:
    # Set up vim.
    - name: Copying ~/.vimrc
      copy:
        src: "{{ playbook_dir }}/.vimrc"
        dest: "{{ ansible_env.HOME }}/.vimrc"

    # Set up .bashrc.
    - name: Updating ~/.bashrc to print timestamp
      blockinfile:
        dest: "{{ ansible_env.HOME }}/.bashrc"
        insertafter: EOF
        create: yes
        marker: "# <-- {mark} ANSIBLE MANAGED BLOCK FOR TIMESTAMP -->"
        marker_begin: "BEGIN"
        marker_end: "END"
        block: |
          PS1="\t $PS1" # Always show timestamp in case of WSL clock drift.
    - name: Update ~/.bashrc for ansible
      blockinfile:
        dest: "{{ ansible_env.HOME }}/.bashrc"
        insertafter: EOF
        create: yes
        marker: "# <-- {mark} ANSIBLE MANAGED BLOCK FOR ANSIBLE -->"
        marker_begin: "BEGIN"
        marker_end: "END"
        block: |
          export PATH=$PATH:$HOME/.local/bin