- hosts: mycomputer
  vars_files:
    - /vars/versions.yaml
  tasks:
    # See
    # - https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install
    # - https://learn.microsoft.com/en-us/dotnet/core/install/macos#install-with-bash-automation
    - name: Download .NET installer
      get_url:
        url: "https://dot.net/v1/dotnet-install.sh"
        dest: "/tmp"
    - name: Changing perm of "/tmp/dotnet-install.sh", adding "+x"
      file:
        dest: /tmp/dotnet-install.sh
        mode: +x
    - name: "Install .NET SDK {{ dotnetVersion }}"
      ansible.builtin.script:
        cmd: "/tmp/dotnet-install.sh --version {{ dotnetVersion }}"
    - name: Remove .NET installer
      file:
        state: absent
        path: "/tmp/dotnet-install.sh"
    - name: Update ~/.bashrc for .NET (Debian)
      when: ansible_facts['os_family'] == "Debian"
      blockinfile:
        dest: "{{ ansible_env.HOME }}/.bashrc"
        insertafter: EOF
        create: yes
        marker: "# <-- {mark} ANSIBLE MANAGED BLOCK FOR .NET -->"
        marker_begin: "BEGIN"
        marker_end: "END"
        block: |
          export DOTNET_ROOT=$HOME/.dotnet
          export PATH="$PATH:$HOME/.dotnet:$HOME/.dotnet/tools"
    - name: Update ~/.zshrc for .NET (Darwin)
      when: ansible_facts['os_family'] == "Darwin"
      blockinfile:
        dest: "{{ ansible_env.HOME }}/.zshrc"
        insertafter: EOF
        create: yes
        marker: "# <-- {mark} ANSIBLE MANAGED BLOCK FOR .NET -->"
        marker_begin: "BEGIN"
        marker_end: "END"
        block: |
          export DOTNET_ROOT=$HOME/.dotnet
          export PATH="$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools"