- hosts: mycomputer
  tasks:
    - name: Set Git name
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ git_name }}"
    - name: Set Git email
      community.general.git_config:
        name: user.email
        scope: global
        value: "{{ git_email }}"
    - name: Set Git editor
      community.general.git_config:
        name: core.editor
        scope: global
        value: vim
    - name: Setup for Azure DevOps
      community.general.git_config:
        name: credential.https://dev.azure.com.useHttpPath
        scope: global
        value: true
