- hosts: localhost
  tasks:
    - name: Install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
        warn: no
    - name: Install node
      shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install node"
      args:
        executable: /bin/bash