- hosts: mycomputer
  tasks:
    - name: Install pip
      become: yes
      apt:
        name: "python3-pip"
    - name: Install Python3.8
      apt:
        name: python3.8
        state: present
        force: true
      become: true
      when: ansible_python_version is version('3.8.0', '<')
    - name: Install virtualenvwrapper
      pip:
        name: virtualenvwrapper
        executable: pip3
        extra_args: --user
    - name: Updating ~/.bashrc to use Python3.8 for virtualenvwrapper
      blockinfile:
        dest: "{{ ansible_env.HOME }}/.bashrc"
        insertafter: EOF
        create: yes
        marker: "# <-- {mark} ANSIBLE MANAGED BLOCK FOR PYTHON 3.8 -->"
        marker_begin: "BEGIN"
        marker_end: "END"
        block: |
          export VIRTUALENVWRAPPER_PYTHON=python3.8
      when: ansible_python_version is version('3.8.0', '<')
    - name: Updating ~/.bashrc for virtualenvwrapper
      blockinfile:
        dest: "{{ ansible_env.HOME }}/.bashrc"
        insertafter: EOF
        create: yes
        marker: "# <-- {mark} ANSIBLE MANAGED BLOCK FOR VIRTUALENVWRAPPER -->"
        marker_begin: "BEGIN"
        marker_end: "END"
        block: |
          export WORKON_HOME=~/.virtualenv
          export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
          source ~/.local/bin/virtualenvwrapper.sh