- hosts: localhost
  pre_tasks:
  - name: Validate Python version is >=3.8
    delegate_to: hostvars[inventory_hostname]['ansible_python_version']
    assert:
      that:
        - ansible_python_version is defined
        - ansible_python_version is version('3.8.0', '>=')
      fail_msg: "'Python' version must be at least 3.8."
    run_once: True
  tasks:
    # Python setup.
    - name: Install pip
      become: yes
      apt:
        name: "python3-pip"
    - name: Install virtualenvwrapper
      pip:
        name: virtualenvwrapper
        executable: pip3
        extra_args: --user
    # Go setup.
    - name: Download Go 1.15.2
      get_url:
        url: "https://golang.org/dl/go1.15.2.linux-amd64.tar.gz"
        dest: "/tmp"
    - name: Install Go
      become: true
      unarchive:
        src: "/tmp/go1.15.2.linux-amd64.tar.gz"
        dest: "/usr/local"
    - name: Remove Go tarball
      file:
        state: absent
        path: "/tmp/go1.15.2.linux-amd64.tar.gz"